export default defineNitroPlugin(async () => {
  const storage = useStorage()

  await storage.setItem('tasks', [
    {
      id: 1,
      title: 'Faire les courses',
      description: 'Acheter des fruits, légumes, et du lait',
      completed: false,
      createdAt: new Date('2024-07-21T10:30:00'),
      category: 1,
    },
    {
      id: 2,
      title: 'Nettoyer la maison',
      completed: false,
      createdAt: new Date('2024-07-20T14:00:00'),
      category: 2,
    },
    {
      id: 3,
      title: 'Appeler le docteur',
      description: 'Prendre rendez-vous pour un bilan de santé',
      completed: true,
      createdAt: new Date('2024-07-19T09:00:00'),
      category: 4,
    },
    {
      id: 4,
      title: 'Lire un livre',
      description: 'Commencer le nouveau roman de science-fiction',
      completed: false,
      createdAt: new Date('2024-07-18T16:30:00'),
      category: 5,
    },
    {
      id: 5,
      title: 'Préparer le dîner',
      description: 'Cuisiner des pâtes à la carbonara',
      completed: false,
      createdAt: new Date('2024-07-17T18:45:00'),
      category: 2,
    },
    {
      id: 6,
      title: 'Envoyer un email au manager',
      description: 'Demander des informations sur le projet en cours',
      completed: true,
      createdAt: new Date('2024-07-16T11:15:00'),
      category: 7,
    },
    {
      id: 7,
      title: 'Aller à la salle de sport',
      description: 'Faire une séance de cardio',
      completed: false,
      createdAt: new Date('2024-07-15T07:30:00'),
      category: 8,
    },
    {
      id: 8,
      title: 'Planifier les vacances',
      description: 'Réserver les billets d\'avion et l\'hôtel',
      completed: false,
      createdAt: new Date('2024-07-14T13:00:00'),
      category: 9,
    },
    {
      id: 9,
      title: 'Visiter la famille',
      description: 'Passer l\'après-midi chez les parents',
      completed: true,
      createdAt: new Date('2024-07-13T15:00:00'),
      category: 10,
    },
    {
      id: 10,
      title: 'Ranger le garage',
      description: 'Organiser les outils et nettoyer les étagères',
      completed: false,
      createdAt: new Date('2024-07-12T11:00:00'),
      category: 2,
    },
    {
      id: 11,
      title: 'Faire du bénévolat',
      description: 'Participer à la collecte de nourriture',
      completed: false,
      createdAt: new Date('2024-07-11T09:30:00'),
      category: 12,
    },
    {
      id: 12,
      title: 'Réparer le vélo',
      description: 'Changer la chambre à air et graisser la chaîne',
      completed: true,
      createdAt: new Date('2024-07-10T10:15:00'),
      category: 13,
    },
    {
      id: 13,
      title: 'Coudre un vêtement',
      description: 'Terminer la jupe commencée la semaine dernière',
      completed: false,
      createdAt: new Date('2024-07-09T14:45:00'),
      category: 14,
    },
    {
      id: 14,
      title: 'Étudier un cours en ligne',
      description: 'Suivre le module sur le design UX',
      completed: true,
      createdAt: new Date('2024-07-08T17:00:00'),
      category: 5,
    },
    {
      id: 15,
      title: 'Méditer',
      description: 'Prendre 20 minutes pour se relaxer',
      completed: false,
      createdAt: new Date('2024-07-07T06:30:00'),
      category: 15,
    },
    {
      id: 16,
      title: 'Faire un puzzle',
      description: 'Assembler le puzzle de 1000 pièces',
      completed: true,
      createdAt: new Date('2024-07-06T20:00:00'),
      category: 16,
    },
    {
      id: 17,
      title: 'Participer à une réunion de travail',
      description: 'Discussion sur le projet de développement',
      completed: false,
      createdAt: new Date('2024-07-05T10:00:00'),
      category: 7,
    },
  ])

  await storage.setItem('categories', [
    { id: 1, name: 'Courses', color: '#A7C7E7' },
    { id: 2, name: 'Ménage', color: '#F4A7B9' },
    { id: 3, name: 'Organisation', color: '#B5EAD7' },
    { id: 4, name: 'Santé', color: '#FFDDC1' },
    { id: 5, name: 'Lecture', color: '#C7CEEA' },
    { id: 6, name: 'Cuisine', color: '#FFD3B6' },
    { id: 7, name: 'Travail', color: '#D4A5A5' },
    { id: 8, name: 'Fitness', color: '#A8D5BA' },
    { id: 9, name: 'Voyage', color: '#E2CFEA' },
    { id: 10, name: 'Famille', color: '#D5CABD' },
    { id: 11, name: 'Social', color: '#A1D2CE' },
    { id: 12, name: 'Bénévolat', color: '#F7C5A8' },
    { id: 13, name: 'Réparation', color: '#E5E5E5' },
    { id: 14, name: 'Artisanat', color: '#E6B8A2' },
    { id: 15, name: 'Bien-être', color: '#CDE6D0' },
    { id: 16, name: 'Loisir', color: '#D6E9F3' },
    { id: 17, name: 'Réunion', color: '#F7D8D8' },
  ])
})
